# Generated by Django 3.0.4 on 2020-05-18 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20200518_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='D:\\Projects\\Portfolio\\portfolio\\static'),
        ),
    ]
